add Shopping cart and Ticket models, dao, service
Alkey/Cinema pull request #5
Opened 2020-10-10 10:05 UTC by Alkey

2020-10-10 10:47 UTC, aleksandr-hrankin commented on src/main/java/com/dev/cinema/dao/impl/TicketDaoImpl.java
> +            session.save(ticket);
я б использовал persist вместо save.

2020-10-10 10:47 UTC, aleksandr-hrankin commented on src/main/java/com/dev/cinema/model/ShoppingCart.java
> +    @OneToMany(fetch = FetchType.EAGER)
Думаю что жадная загрузка не самый лучший вариант

2020-10-10 10:47 UTC, aleksandr-hrankin commented on src/main/java/com/dev/cinema/model/ShoppingCart.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
Если мы юзаем @MapsId, то нам эта аннотация не нужна

2020-10-12 07:48 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/dao/impl/TicketDaoImpl.java
> +            session.save(ticket);
@aleksandr-hrankin it doesn't really matter here

2020-10-12 07:56 UTC, KseniiaMakarova requested changes

2020-10-12 07:56 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/MainApp.java
> +                    .getInstance(ShoppingCartService.class);
can we create an injector variable?

2020-10-12 07:56 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/MainApp.java
> +        ShoppingCart shoppingCart = shoppingCartService.getByUser(user);
here you are doing the same call twice in a row

2020-10-12 07:56 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/ShoppingCart.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
I agree

2020-10-12 07:56 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/ShoppingCart.java
> +    @OneToMany(fetch = FetchType.EAGER)
let's remove eager fetching - in general, this is considered bad practice
and find another way to get tickets along with the shopping cart

2020-10-12 10:21 UTC, KseniiaMakarova approved these changes

2020-10-12 10:28 UTC, merged